passenger_version: 2.2.5
passenger_root: "#{ruby_prefix}/lib/ruby/gems/1.8/gems/passenger-#{passenger_version}"
passenger_ruby: "#{ruby_prefix}/bin/ruby"
passenger_lib: "#{passenger_root}/ext/apache2/mod_passenger.so"
passenger_listen_port: 7000
passenger_listen_ssl_port: 7001
max_app_connections: 20

role_dependencies:
  passenger: [apache]

roles:
  passenger:
    packages: [apache2-mpm-prefork, apache2-prefork-dev]
    gems: [fastthread, rack, [passenger, "#{passenger_version}"]]
